spring.application.name=finanacialmanagement
spring.datasource.url=jdbc:postgresql://localhost:5433/financial_management
spring.datasource.username=finance_user
spring.datasource.password=finance_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true